els-ASAP auto commit file/tag ctdb-2.5.1-1.el6.src.rpm

diff --git a/src/config/statd-callout b/src/config/statd-callout
--- a/src/config/statd-callout
+++ b/src/config/statd-callout
@@ -1,49 +1,80 @@
 #!/bin/sh
 
+# This must run as root as CTDB tool commands need to access CTDB socket
+[ $(id -u) -eq 0 ] || exec sudo "$0" "$@"
+
 # this script needs to be installed so that statd points to it with the -H 
 # command line argument. The easiest way to do that is to put something like this in 
 # /etc/sysconfig/nfs:
 #   STATD_HOSTNAME="myhostname -H /etc/ctdb/statd-callout"
 
-[ -z "$CTDB_BASE" ] && {
-    export CTDB_BASE="/etc/ctdb"
-}
+[ -n "$CTDB_BASE" ] || \
+    export CTDB_BASE=$(cd -P $(dirname "$0") ; echo "$PWD")
 
 . $CTDB_BASE/functions
+
+# Overwrite this so we get some logging
+die ()
+{
+    script_log "statd-callout" "$@"
+    exit 1
+}
+
 loadconfig ctdb
 loadconfig nfs
 
-[ -z "$STATD_SHARED_DIRECTORY" ] && {
-	echo STATD_SHARED_DIRECTORY not configured. statd-callout failed.
-	exit 0
-}
+[ -n "$NFS_HOSTNAME" ] || \
+    die "NFS_HOSTNAME is not configured. statd-callout failed"
 
-[ -d $STATD_SHARED_DIRECTORY ] || exit 0
-
-[ -z $NFS_HOSTNAME ] && {
-	echo NFS_HOSTNAME is not configured. statd-callout failed.
-	exit 0
-}
+# A handy newline
+nl="
+"
 
 case "$1" in
-  add-client)
-	# the callout does not tell us to which ip the client connected
-	# so we must add it to all the ips that we serve
-        for f in $CTDB_BASE/state/statd/ip/*; do
-	    ip=`basename $f`
-	    [ -d $STATD_SHARED_DIRECTORY/$ip ] || /bin/mkdir $STATD_SHARED_DIRECTORY/$ip
-	    touch $STATD_SHARED_DIRECTORY/$ip/$2
-	done
+    add-client)
+	# statd does not tell us to which IP the client connected so
+	# we must add it to all the IPs that we serve
+	cip="$2"
+	pnn=$(ctdb xpnn | sed -e 's/.*://')
+	date=$(date '+%s')
+	ctdb ip -Y |
+	tail -n +2 | {
+	    # This all needs to be in the end of the pipe so it
+	    # doesn't get lost
+	    items=""
+	    while IFS=":" read x sip node x ; do
+		[ "$node" = "$pnn" ] || continue # not us
+		key="statd-state@${sip}@${cip}"
+		item="\"${key}\" \"${date}\""
+		items="${items}${items:+${nl}}${item}"
+	    done
+	    if ! echo "$items" | ctdb ptrans "ctdb.tdb" ; then
+		die "Failed to add clients"
+	    fi
+	}
 	;;
   del-client)
-	# the callout does not tell us to which ip the client connected
-	# so we must add it to all the ips that we serve
-        for f in $CTDB_BASE/state/statd/ip/*; do
-	    ip=`basename $f`
-	    /bin/rm -f $STATD_SHARED_DIRECTORY/$ip/$2
-	done
+	# statd does not tell us from which IP the client disconnected
+	# so we must add it to all the IPs that we serve
+	cip="$2"
+	pnn=$(ctdb xpnn | sed -e 's/.*://')
+	ctdb ip -Y |
+	tail -n +2 | {
+	    # This all needs to be in the end of the pipe so it
+	    # doesn't get lost
+	    items=""
+	    while IFS=":" read x sip node x ; do
+		[ "$node" = "$pnn" ] || continue # not us
+		key="statd-state@${sip}@${cip}"
+		item="\"${key}\" \"\""
+		items="${items}${items:+${nl}}${item}"
+	    done
+	    if ! echo "$items" | ctdb ptrans "ctdb.tdb" ; then
+		die "Failed to delete clients"
+	    fi
+	}
 	;;
-  notify)
+    notify)
 	# we must restart the lockmanager (on all nodes) so that we get
 	# a clusterwide grace period (so other clients dont take out
 	# conflicting locks through other nodes before all locks have been
@@ -55,49 +86,29 @@ case "$1" in
 	#echo 0 > /proc/sys/net/ipv4/tcp_max_tw_buckets
 	#echo 0 > /proc/sys/net/ipv4/tcp_max_orphans
 
-	# rebuild the state directory for the local statd to use the correct
-	# state value and to initally send notifications to all clients
+	# Delete the notification list for statd, we dont want it to 
+	# ping any clients
 	rm -f /var/lib/nfs/statd/sm/*
 	rm -f /var/lib/nfs/statd/sm.bak/*
-	cat $STATD_SHARED_DIRECTORY/state >/var/lib/nfs/statd/state
-
 
 	# we must keep a monotonically increasing state variable for the entire
 	# cluster  so state always increases when ip addresses fail from one
 	# node to another
-	[ ! -f $STATD_SHARED_DIRECTORY/state ] && {
-		echo 1 | awk '{printf("%c%c%c%c", $0, $0/256, $0/256/256, $0/256/256/256);}' >$STATD_SHARED_DIRECTORY/state
-	}
-	# read current state
-	STATE=`od -t d4 $STATD_SHARED_DIRECTORY/state | head -1 | sed -e "s/^[0-9]*[^0-9]*//"`
-	# write current state+2 back to the state file
-	# the /2 *2 are to ensure that state is odd. state must be odd.
-	STATE=`expr $STATE "/" 2 "*" 2 "+" 3`
-	echo $STATE | awk '{printf("%c%c%c%c", $0, $0/256, $0/256/256, $0/256/256/256);}' >$STATD_SHARED_DIRECTORY/state
-	
-
+	# We use epoch and hope the nodes are close enough in clock.
+	# Even numbers mean service is shut down, odd numbers mean
+	# service is started.
+	state_even=$(( $(date '+%s') / 2 * 2))
 
 	# we must also let some time pass between stopping and restarting the
 	# lockmanager since othervise there is a window where the lockmanager
 	# will respond "strangely" immediately after restarting it, which
 	# causes clients to fail to reclaim the locks.
 	# 
-	startstop_nfslock stop > /dev/null 2>&1
-	sleep 2
-
-	# copy all monitored clients on this node to the local lockmanager
-	for f in `/bin/ls $CTDB_BASE/state/statd/ip/* 2>/dev/null`; do
-	    ip=`basename $f`
-	    [ -d $STATD_SHARED_DIRECTORY/$ip ] && [ -x /usr/bin/smnotify ] && {
-		for g in `/bin/ls $STATD_SHARED_DIRECTORY/$ip/* 2>/dev/null`; do
-			client=`basename $g`
-			touch /var/lib/nfs/statd/sm/$client
-		done
-	    }
-	done
-
-	# now start lockmanager again with the new state directory.
-	startstop_nfslock start > /dev/null 2>&1
+	if [ "${CTDB_NFS_SERVER_MODE:-${NFS_SERVER_MODE}}" != "ganesha" ] ; then
+            startstop_nfslock stop >/dev/null 2>&1
+            sleep 2
+            startstop_nfslock start >/dev/null 2>&1
+	fi
 
 	# we now need to send out additional statd notifications to ensure
 	# that clients understand that the lockmanager has restarted.
@@ -127,23 +138,46 @@ case "$1" in
 	# Both 2a and 2b are commonly used in lockmanagers since they maximize
 	# probability that the client will accept the statd notify packet and
 	# not just ignore it.
-        for f in `/bin/ls $CTDB_BASE/state/statd/ip/* 2>/dev/null`; do
-	    ip=`basename $f`
-	    [ -d $STATD_SHARED_DIRECTORY/$ip ] && [ -x /usr/bin/smnotify ] && {
-		for g in `/bin/ls $STATD_SHARED_DIRECTORY/$ip/* 2>/dev/null`; do
-			client=`basename $g`
-#			/bin/rm -f $g
-			# send out notifications from the "correct" address
-			# (the same addresse as where the lock was taken out
-			# on)   some clients require that the source address
-			# matches where the lock was taken out.
-			# also send it both as a name that the client
-			# hopefully can resolve into the server ip and
-			# and also by specifying the raw ip address as name.
-			/usr/bin/smnotify --client=$client --ip=$ip --server=$ip --stateval=$STATE
-			/usr/bin/smnotify --client=$client --ip=$ip --server=$NFS_HOSTNAME --stateval=$STATE
-		done
-	    }
+	# For all IPs we serve, collect info and push to the config database
+	pnn=$(ctdb xpnn | sed -e 's/.*://')
+
+	# Construct a sed expression to take catdb output and produce pairs of:
+	#   server-IP client-IP
+	# but only for the server-IPs that are hosted on this node.
+	sed_expr=$(ctdb ip | tail -n +2 |
+	    awk -v pnn=$pnn 'pnn == $2 { printf "s/^key.*=.*statd-state@\\(%s\\)@\\([^\"]*\\).*/\\1 \\2/p\n", gensub(/\./, "\\\\.", "g", $1) }')
+
+	statd_state=$(ctdb catdb ctdb.tdb | sed -n "$sed_expr" | sort)
+	[ -n "$statd_state" ] || exit 0
+
+	# The following is dangerous if this script times out before
+	# all of the smnotify commands are run.  Revert to individual
+	# pdelete commands for now and consider optimising smnotify to
+	# read all the data from stdin and then run it in the
+	# background.
+	#
+	# Delete all the items from the TDB
+	#if ! echo "$statd_state" | \
+	#    awk '{ printf "\"statd-state@%s@%s\" \"\"\n", $1, $2 }') | \
+	#    ctdb ptrans ctdb.tdb ; then
+
+	#    die "Yikes!"
+	#fi
+
+	prev=""
+	echo "$statd_state" |
+	while read sip cip ; do
+	    # Delete the entry from the DB
+	    ctdb pdelete ctdb.tdb "statd-state@${sip}@${cip}"
+	    # Reset stateval for each serverip
+	    [ "$sip" = "$prev" ] || stateval="$state_even"
+	    # Send notifies for server shutdown
+	    smnotify --client=$cip --ip=$sip --server=$sip --stateval=$stateval
+	    smnotify --client=$cip --ip=$sip --server=$NFS_HOSTNAME --stateval=$stateval
+	    # Send notifies for server startup
+	    stateval=$(($stateval + 1))
+	    smnotify --client=$cip --ip=$sip --server=$sip --stateval=$stateval
+	    smnotify --client=$cip --ip=$sip --server=$NFS_HOSTNAME --stateval=$stateval
 	done
 	;;
 esac
diff --git a/src/tools/ctdb_diagnostics b/src/tools/ctdb_diagnostics
--- a/src/tools/ctdb_diagnostics
+++ b/src/tools/ctdb_diagnostics
@@ -1,15 +1,84 @@
 #!/bin/sh
 # a script to test the basic setup of a CTDB/Samba install 
 # tridge@samba.org September 2007
+# martin@meltin.net August 2010
+
+usage ()
+{
+    cat >&2 <<EOF
+Usage: ctdb_diagnostics [OPTION] ...
+  options:
+    -n <nodes>  Comma separated list of nodes to operate on
+    -c          Ignore comment lines (starting with '#') in file comparisons
+    -w          Ignore whitespace in file comparisons
+    --no-ads    Do not use commands that assume an Active Directory Server
+EOF
+    exit 1
+
+}
+
+nodes=$(ctdb listnodes -Y | cut -d: -f2)
+bad_nodes=""
+diff_opts=
+no_ads=false
+
+parse_options ()
+{
+    temp=$(getopt -n "ctdb_diagnostics" -o "n:cwh" -l no-ads,help -- "$@")
+
+    [ $? != 0 ] && usage
+
+    eval set -- "$temp"
+
+    while true ; do
+	case "$1" in
+	    -n) nodes=$(echo "$2" | sed -e 's@,@ @g') ; shift 2 ;;
+	    -c) diff_opts="${diff_opts} -I ^#.*" ; shift ;;
+	    -w) diff_opts="${diff_opts} -w" ; shift ;;
+	    --no-ads) no_ads=true ; shift ;;
+	    --) shift ; break ;;
+	    -h|--help|*) usage ;;
+	esac
+    done
+
+    [ $# -ne 0 ] && usage
+}
+
+parse_options "$@"
+
+# Use 5s ssh timeout if EXTRA_SSH_OPTS doesn't set a timeout.
+case "$EXTRA_SSH_OPTS" in
+    *ConnectTimeout=*) : ;;
+    *)
+	export EXTRA_SSH_OPTS="${EXTRA_SSH_OPTS} -o ConnectTimeout=5"
+esac
+
+# Filter nodes.  Remove any nodes we can't contact from $node and add
+# them to $bad_nodes.
+_nodes=""
+for _i in $nodes ; do
+    if onnode $_i true >/dev/null 2>&1 ; then
+	_nodes="${_nodes}${_nodes:+ }${_i}"
+    else
+	bad_nodes="${bad_nodes}${bad_nodes:+,}${_i}"
+    fi
+done
+nodes="$_nodes"
+
+nodes_comma=$(echo $nodes | sed -e 's@[[:space:]]@,@g')
 
 PATH="$PATH:/sbin:/usr/sbin:/usr/lpp/mmfs/bin"
 
 # list of config files that must exist and that we check are the same 
-# on all nodes
-CONFIG_FILES_MUST="/etc/krb5.conf /etc/hosts /etc/ctdb/nodes /etc/sysconfig/ctdb /etc/resolv.conf /etc/nsswitch.conf /etc/sysctl.conf /etc/samba/smb.conf /etc/fstab /etc/multipath.conf /etc/pam.d/system-auth /etc/sysconfig/nfs /etc/exports /etc/vsftpd/vsftpd.conf"
+# on the nodes
+if [ -d /etc/sysconfig ] ; then
+    CONFIG_FILES_MUST="/etc/krb5.conf /etc/hosts /etc/ctdb/nodes /etc/sysconfig/ctdb /etc/resolv.conf /etc/nsswitch.conf /etc/sysctl.conf /etc/samba/smb.conf /etc/fstab /etc/multipath.conf /etc/pam.d/system-auth /etc/sysconfig/nfs /etc/exports /etc/vsftpd/vsftpd.conf"
+else
+    CONFIG_FILES_MUST="/etc/krb5.conf /etc/hosts /etc/ctdb/nodes /etc/default/ctdb /etc/resolv.conf /etc/nsswitch.conf /etc/sysctl.conf /etc/samba/smb.conf /etc/fstab /etc/multipath.conf /etc/pam.d/system-auth /etc/default/nfs /etc/exports /etc/vsftpd/vsftpd.conf"
+fi
 
 # list of config files that may exist and should be checked that they
-# are the same on all nodes
+# are the same on the nodes
 CONFIG_FILES_MAY="/etc/ctdb/public_addresses /etc/ctdb/static-routes"
 
 2>&1
@@ -41,67 +110,98 @@ show_file() {
 }
 
 show_all() {
-    echo "running $1 on all nodes"
-    onnode all "hostname; date; $1 2>&1 | sed 's/^/  /'"
+    echo "running $1 on nodes $nodes_comma"
+    onnode $nodes_comma "hostname; date; $1 2>&1 | sed 's/^/  /'" 2>&1
 }
 
-ERRORS="/tmp/diag_err.$$"
-NUM_NODES=`wc -l < /etc/ctdb/nodes`
-MAX_NODE=`expr $NUM_NODES - 1`
-NUM_ERRORS=0
-cat <<EOF
-Diagnosis started on a $NUM_NODES node cluster. The following node list will be used:
-EOF
-show_file /etc/ctdb/nodes
+show_and_compare_files () {
 
+    fmt="$1" ; shift
+
+    for f ; do
+	first=true
+
+	for n in $nodes ; do
+
+	    if $first ; then
+		onnode $n [ -r "$f" ] || {
+		    msg=$(printf "$fmt" "$f" $n)
+		    error "$msg"
+		    continue 2;
+		}
+
+		fstf=$tmpdir/`basename $f`.node$n
+		onnode $n cat $f > $fstf 2>&1
+
+		echo "  ================================"
+		echo "  File (on node $n): $f"
+		echo "  `onnode $n ls -l $f 2>&1`"
+		cat "$fstf" | sed 's/^/  /'
+		echo "  ================================"
+		first=false
+	    else
+		echo "Testing for same config file $f on node $n"
+		tmpf=$tmpdir/`basename $f`.node$n
+		onnode $n cat $f > $tmpf 2>&1
+		diff $diff_opts $fstf $tmpf >/dev/null 2>&1 || {
+		    error "File $f is different on node $n"
+		    diff -u $diff_opts $fstf $tmpf
+		}
+		rm -f $tmpf
+	    fi
+	done
+
+	rm -f $fstf
+    done
+}
+
+if ! tmpdir=$(mktemp -d) ; then
+    echo "Unable to create a temporary directory"
+    exit 1
+fi
+ERRORS="${tmpdir}/diag_err"
+NUM_ERRORS=0
+
+cat <<EOF
+Diagnosis started on these nodes:
+$nodes_comma
+EOF
+
+if [ -n "$bad_nodes" ] ; then
+    cat <<EOF
+
+NOT RUNNING DIAGNOSTICS on these uncontactable nodes:
+$bad_nodes
+EOF
+
+fi
+
+cat <<EOF
+
+For reference, here is the nodes file on the current node...
+EOF
+
+show_file /etc/ctdb/nodes
 
 cat <<EOF
 --------------------------------------------------------------------
-Comping critical config files on all nodes
+Comping critical config files on nodes $nodes_comma
 EOF
 
-for f in $CONFIG_FILES_MUST; do
- [ -r "$f" ] || {
-    error "$f is missing on this node"
-    continue;
- }
- show_file $f
- for i in `seq 0 $MAX_NODE`; do
-     echo "Testing for same config file $f on node $i"
-     tmpf=/tmp/`basename $f`.node$i
-     onnode $i cat $f > $tmpf 2>&1
-     cmp $f $tmpf 2>&1 || {
-	 error "File $f is different on node $i"
-	 diff -u $f $tmpf
-     }
-     rm -f $tmpf
- done
-done
+show_and_compare_files \
+    "%s is missing on node %d" \
+    $CONFIG_FILES_MUST
 
-for f in $CONFIG_FILES_MAY; do
- [ -r "$f" ] || {
-    echo "Optional file $f is not present on local node"
-    continue;
- }
- show_file $f
- for i in `seq 0 $MAX_NODE`; do
-     echo "Testing for same config file $f on node $i"
-     tmpf=/tmp/`basename $f`.node$i
-     onnode $i cat $f > $tmpf 2>&1
-     cmp $f $tmpf 2>&1 || {
-	 error "File $f is different on node $i"
-	 diff -u $f $tmpf
-     }
-     rm -f $tmpf
- done
-done
+show_and_compare_files \
+    "Optional file %s is not present on node %d" \
+    $CONFIG_FILES_MAY
 
 cat <<EOF
 --------------------------------------------------------------------
 Checking for clock drift
 EOF
 t=`date +%s`
-for i in `seq 0 $MAX_NODE`; do
+for i in $nodes; do
     t2=`onnode $i date +%s`
     d=`expr $t2 - $t`
     if [ $d -gt 30 -o $d -lt -30 ]; then
@@ -131,6 +231,8 @@ EOF
 show_all "ctdb status; ctdb ip"
 show_all "ctdb statistics"
 show_all "ctdb uptime"
+show_all "ctdb listvars"
+show_all "ctdb getdbmap"
 
 echo "Showing log.ctdb"
 show_all "test -f /var/log/log.ctdb && tail -100 /var/log/log.ctdb"
@@ -188,49 +290,29 @@ show_all "/usr/sbin/nfsstat -v"
     done
 }
 
-[ -d /usr/lpp/mmfs ] && {
-cat <<EOF
---------------------------------------------------------------------
-Showing GPFS status and recent log entries
-EOF
- show_all "tail -100 /var/adm/ras/mmfs.log.latest"
- show_all "/usr/lpp/mmfs/bin/mmlsconfig"
- show_all "/usr/lpp/mmfs/bin/mmlsfs all"
- show_all "/usr/lpp/mmfs/bin/mmlsnsd"
- show_all "/usr/lpp/mmfs/bin/mmlsnsd -X"
- show_all "/usr/lpp/mmfs/bin/mmfsadm dump version"
- show_all "/usr/lpp/mmfs/bin/mmfsadm dump waiters"
- show_all "/usr/lpp/mmfs/bin/mmlsmount all"
- show_all "/usr/lpp/mmfs/bin/mmlsquota"
- show_all "/usr/lpp/mmfs/bin/mmlscluster"
- show_all "/usr/lpp/mmfs/bin/mmlsmgr"
- devlist=`mmlsfs all|grep ^File.system.attributes | cut -d/ -f3 | cut -d: -f1`
- for d in $devlist; do
-     show_all "mmdf $d"
-     show_all "mmlsdisk $d"
-     show_all "mmlsfileset $d"
-     show_all "mmlspolicy $d"
-     show_all "mmlssnapshot $d"
- done
- fslist=`mount|grep type.gpfs|awk '{print $1}'`
- for fs in $fslist; do
-     show_all "/usr/lpp/mmfs/bin/mmlssnapshot $fs"
-     show_all "/usr/lpp/mmfs/bin/mmlsdisk $fs"
-     show_all "/usr/lpp/mmfs/bin/mmlsfileset $fs"
- done
-}
-
 cat <<EOF
 --------------------------------------------------------------------
 Showing Samba status
 EOF
 show_all "smbstatus -n -B"
-show_all "net ads testjoin"
+if $no_ads ; then
+    echo
+    echo "Skipping \"net ads testjoin\" as requested"
+    echo
+else
+    show_all "net ads testjoin"
+fi
 show_all "net conf list"
 show_all "lsof -n | grep smbd"
 show_all "lsof -n | grep ctdbd"
 show_all "netstat -tan"
-show_all "net ads info"
+if $no_ads ; then
+    echo
+    echo "Skipping \"net ads info\" as requested"
+    echo
+else
+    show_all "net ads info"
+fi
 show_all "date"
 show_all "smbclient -U% -L 127.0.0.1"
 WORKGROUP=`testparm -s --parameter-name=WORKGROUP 2> /dev/null`
@@ -246,5 +328,8 @@ echo "Diagnostics finished with $NUM_ERRORS errors"
     cat $ERRORS
     rm -f $ERRORS
 }
+
+rm -rf "$tmpdir"
+
 exit $NUM_ERRORS
 
